C_SOURCES += \
HAL_Driver/Src/stm32f0xx_hal.c \
HAL_Driver/Src/stm32f0xx_hal_adc.c \
HAL_Driver/Src/stm32f0xx_hal_adc_ex.c \
HAL_Driver/Src/stm32f0xx_hal_can.c \
HAL_Driver/Src/stm32f0xx_hal_cec.c \
HAL_Driver/Src/stm32f0xx_hal_comp.c \
HAL_Driver/Src/stm32f0xx_hal_cortex.c \
HAL_Driver/Src/stm32f0xx_hal_crc.c \
HAL_Driver/Src/stm32f0xx_hal_crc_ex.c \
HAL_Driver/Src/stm32f0xx_hal_dac.c \
HAL_Driver/Src/stm32f0xx_hal_dac_ex.c \
HAL_Driver/Src/stm32f0xx_hal_dma.c \
HAL_Driver/Src/stm32f0xx_hal_flash.c \
HAL_Driver/Src/stm32f0xx_hal_flash_ex.c \
HAL_Driver/Src/stm32f0xx_hal_gpio.c \
HAL_Driver/Src/stm32f0xx_hal_i2c.c \
HAL_Driver/Src/stm32f0xx_hal_i2c_ex.c \
HAL_Driver/Src/stm32f0xx_hal_i2s.c \
HAL_Driver/Src/stm32f0xx_hal_irda.c \
HAL_Driver/Src/stm32f0xx_hal_iwdg.c \
HAL_Driver/Src/stm32f0xx_hal_pcd.c \
HAL_Driver/Src/stm32f0xx_hal_pcd_ex.c \
HAL_Driver/Src/stm32f0xx_hal_pwr.c \
HAL_Driver/Src/stm32f0xx_hal_pwr_ex.c \
HAL_Driver/Src/stm32f0xx_hal_rcc.c \
HAL_Driver/Src/stm32f0xx_hal_rcc_ex.c \
HAL_Driver/Src/stm32f0xx_hal_rtc.c \
HAL_Driver/Src/stm32f0xx_hal_rtc_ex.c \
HAL_Driver/Src/stm32f0xx_hal_smartcard.c \
HAL_Driver/Src/stm32f0xx_hal_smartcard_ex.c \
HAL_Driver/Src/stm32f0xx_hal_smbus.c \
HAL_Driver/Src/stm32f0xx_hal_spi.c \
HAL_Driver/Src/stm32f0xx_hal_spi_ex.c \
HAL_Driver/Src/stm32f0xx_hal_tim.c \
HAL_Driver/Src/stm32f0xx_hal_tim_ex.c \
HAL_Driver/Src/stm32f0xx_hal_tsc.c \
HAL_Driver/Src/stm32f0xx_hal_uart.c \
HAL_Driver/Src/stm32f0xx_hal_uart_ex.c \
HAL_Driver/Src/stm32f0xx_hal_usart.c \
HAL_Driver/Src/stm32f0xx_hal_wwdg.c \
HAL_Driver/Src/stm32f0xx_ll_adc.c \
HAL_Driver/Src/stm32f0xx_ll_comp.c \
HAL_Driver/Src/stm32f0xx_ll_crc.c \
HAL_Driver/Src/stm32f0xx_ll_crs.c \
HAL_Driver/Src/stm32f0xx_ll_dac.c \
HAL_Driver/Src/stm32f0xx_ll_dma.c \
HAL_Driver/Src/stm32f0xx_ll_exti.c \
HAL_Driver/Src/stm32f0xx_ll_gpio.c \
HAL_Driver/Src/stm32f0xx_ll_i2c.c \
HAL_Driver/Src/stm32f0xx_ll_pwr.c \
HAL_Driver/Src/stm32f0xx_ll_rcc.c \
HAL_Driver/Src/stm32f0xx_ll_rtc.c \
HAL_Driver/Src/stm32f0xx_ll_spi.c \
HAL_Driver/Src/stm32f0xx_ll_tim.c \
HAL_Driver/Src/stm32f0xx_ll_usart.c \
HAL_Driver/Src/stm32f0xx_ll_utils.c